name: pre-commit

on:
  pull_request:
  push:
    branches: [source]

permissions:
  contents: read

jobs:
  pre-commit:
    if: github.repository == 'metal3-io/metal3-io.github.io'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
