name: pre-commit

on:
  pull_request:
  push:
    branches: [source]

permissions:
  contents: read

jobs:
  pre-commit:
    if: github.repository == 'metal3-io/metal3-io.github.io'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
